services:
  caddy:
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "3001:3000"
